import { ClerkProvider } from '@clerk/nextjs/app-beta';
import '../globals.css';
import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import Background from '@/components/background/Background';
import Header from '@/components/Header';

const lexendDeca = Lexend_Deca({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${lexendDeca.className} max-w-[1078px] mx-auto px-[24px]`}>
          <Header />
          {children}
          <Background />
        </body>
      </html>
    </ClerkProvider>
  );
}
