import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import Background from '@/components/background/Background';

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${lexendDeca.className} min-h-[100svh] flex items-center justify-center bg-near-white`}
        >
          <Background />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
